---
title: FAS6337C - Lab 3
author: Marcel Gietzmann-Sanders
---

# Load and Split the Data

```{r}
setwd("/workspaces/schooling/population_dynamics/lab_3/")
trout_data <- read.table("data/trout.txt", header=T, sep="") 
head(trout_data)
```

```{r}
ch_data <- na.omit(
    trout_data[trout_data$bay == 'CharlotteHarbor',]
)
ch_data <- ch_data[order(ch_data$yearsold),]
ir_data <- na.omit(
    trout_data[trout_data$bay == 'IndianRiver',]
)
ir_data <- ir_data[order(ir_data$yearsold),]
```

# Function to Map a Vector to Parameters

```{r}
map_columns <- function(v, cols) {
    c <- rep(0, 8)
    i <- 0
    for (col in cols) {
        i <- i + 1
        if (endsWith(col, 'Linf')) {
            j <- 1
        } else if (endsWith(col, 'vbk')) {
            j <- 3
        } else if (endsWith(col, 'tknot')) {
            j <- 5
        } else {
            j <- 7
        }

        if (startsWith(col, 'ch_')) {
            c[j] <- v[i]
        } else if (startsWith(col, 'ir_')) {
            c[j+1] <- v[i]
        } else {
            c[j] <- v[i]
            c[j+1] <- v[i]
        }
    }
    return(c)
}

map_columns(c(1, 3, 2, 3, 4), c('ir_Linf', 'ch_Linf', 'vbk', 'tknot', 'sig'))
```

# Basic Functions

```{r}

predict_length <- function(yearsold, Linf, vbk, tknot) {
  pred_tl <- Linf * (1 - exp(-vbk * (yearsold - tknot)))
  return(pred_tl)
}

get_likelihood <- function(yearsold, tl, Linf, vbk, tknot, sig) {
  pred_tl <- predict_length(yearsold, Linf, vbk, tknot)
  NLL <- -1 * sum(dnorm(tl, pred_tl, sig, log=T), na.rm=T)
  return(NLL)
}
```

# Function to Fit on Arbitrary Columns

```{r}
do_likelihood_fit <- function(v, cols, runs) {
  objective <- function(v) {
    c <- map_columns(v, cols)

    ch_Linf <- exp(c[1])
    ch_vbk <- c[3]
    ch_tknot <- c[5]
    ch_sig <- exp(c[7])

    ir_Linf <- exp(c[2])
    ir_vbk <- c[4]
    ir_tknot <- c[6]
    ir_sig <- exp(c[8])

    ch_NLL <- get_likelihood(ch_data$yearsold, ch_data$tl, ch_Linf, ch_vbk, ch_tknot, ch_sig)
    ir_NLL <- get_likelihood(ir_data$yearsold, ir_data$tl, ir_Linf, ir_vbk, ir_tknot, ir_sig)

    NLL <- ch_NLL + ir_NLL
    return(NLL)
  }

  for (i in 1:runs) {
    fit <- optim(v, objective, hessian=T)
    v <- fit$par
  }
  return(fit)
}
```

# Let's Try It!
To share a parameter just make sure it doesn't have a prefix ('ch_' or 'ir_').

We can start by sharing $L_{\infty}$:
```{r}
v <- c(
  6.7, 0.2, -1.5,  3.7,
  0.2, -1.2,  4.1
) 
cols <- c(
  'Linf', 'ch_vbk', 'ch_tknot', 'ch_sig',
  'ir_vbk', 'ir_tknot', 'ir_sig'
)
(fit <- do_likelihood_fit(v, cols, 25))
```

Or we can share $\sigma$:
```{r}
v <- c(
  6.7, 0.2, -1.5,  3.7,
  6.9,  0.2, -1.2
) 
cols <- c(
  'ch_Linf', 'ch_vbk', 'ch_tknot', 'sig',
  'ir_Linf', 'ir_vbk', 'ir_tknot'
)
(fit <- do_likelihood_fit(v, cols, 25))
```